#!/usr/bin/env bash

set -e

PLUGIN_ALIYUN_OSS_ENDPOINT=${PLUGIN_ALIYUN_OSS_ENDPOINT:-"false"}
PLUGIN_ALIYUN_ACCESS_KEY_ID=${PLUGIN_ALIYUN_ACCESS_KEY_ID:-"false"}
PLUGIN_ALIYUN_ACCESS_KEY_SECRET=${PLUGIN_ALIYUN_ACCESS_KEY_SECRET:-"false"}
